#!/usr/bin/python
class student():
    def __init__(self,fname,lname,age,section): 
        self.firstname = fname
        self.lastname = lname
        self.age = age
        self.section = section

subject = student( "Mike", "Doussey", 35, "male")
print(subject)